import os
from volcenginesdkarkruntime import Ark

import config

client = Ark(
    base_url='https://ark.cn-beijing.volces.com/api/v3',
    api_key=config.DOUBAO_API_KEY
)

response = client.responses.create(
    model="doubao-seed-1-6-251015",
    input=[
            {
             "role": "system",
             "content": "你是辩论小能手，这是你的观点,Religion is not violent or not violent, its followers are.\nSo recently I've seen a lot of posts condemning Islam as a violent religion or a sexist religion. I point out that many Christians follow the bible which has numerous examples of sexism, but in application, there are numerous branches of Christianity that are no more sexist than secula"
            },
            {
                "role": "assistant",
                "content": "Religion is not violent or not violent, its followers are.\nSo recently I've seen a lot of posts condemning Islam as a violent religion or a sexist religion. I point out that many Christians follow the bible which has numerous examples of sexism, but in application, there are numerous branches of Christianity that are no more sexist than secula"
            },
            {
            "role": "user",
            "content":"""Thank you, Mr./Madam Chairman, fellow debaters, and audience. Let me first affirm the rationality of the opposing debater's core perspective — that religion, as a set of doctrinal and value systems, does not inherently carry the label of "violence". Its practical presentation indeed depends on how believers interpret and practice it. This perspective reminds us to avoid simplistic labeling of any religion, which I fully agree with.
To further deepen this discussion, I want to explore a premise with you: when we evaluate the "equality" or "violence" of different religious practices, do we unconsciously use a consistent cognitive framework? You mentioned that many Christian branches have become non-sexist despite the Bible containing relevant textual expressions. I'm curious — in your observation, what is the key factor that allows these Christian branches to achieve such positive evolution? Is it the adaptation to the social environment they are in, or the subjective initiative of believers in interpretation? For instance, regarding the traditional statements about gender roles in the Bible, how do you think these enlightened denominations balance the original text and modern equality concepts?

I fully agree with your insight that "interpretation and adaptation" are the key. If we follow this logic, we can find that similar adaptation and interpretation also exist in the Islamic world. For example, in some Islamic communities, there are practices that respect women's right to education and career development, and believers also interpret religious texts in combination with modern society. But here's a question worth thinking about: when we talk about the progress of Christianity, we often take the initiative to associate it with "the positive adaptation of believers"; but when it comes to Islam, why do many discussions (including some public opinions we are exposed to) tend to directly link individual conservative practices to the religion itself?

Let me put it another way — suppose there is a conservative Christian group that adheres to traditional gender concepts, and a progressive Islamic group that advocates gender equality. When evaluating these two groups, will we naturally attribute the conservatism of the former to "individual group choices" and the progress of the latter to "special cases"? If such a cognitive tendency exists, is it because the social and cultural background we are in has given us a preset cognitive orientation towards different religions? This is not to accuse you of having prejudices, but to explore whether our evaluation criteria will be unconsciously affected by the dominant discourse environment.

Speaking of gender equality, which you mentioned, I want to discuss with you the diversity of equality concepts. You must have noticed that different cultures have different understandings of "gender equality". For example, in some Western societies, the focus of gender equality is on "individual rights and equal participation in public affairs"; while in some Eastern or Islamic cultures, it may be more focused on "the harmony and balance of family and social roles". Here's a specific scenario for you: a woman in an Islamic community chooses to focus on family care while enjoying the right to education and property inheritance protected by local laws, and she says this choice is in line with her understanding of religious teachings and personal values. At the same time, a woman in a Christian community chooses to engage in public office and believes that this is the embodiment of equality given by her religion. Do you think these two choices can both be regarded as the embodiment of "gender equality" under different cultural contexts? If we only recognize the latter as "real equality" and question the former, is this equivalent to equating "Western cultural norms" with "universal equality standards"? And this kind of cognitive tendency, will it make us unconsciously ignore the diversity of cultural expressions of equality?

Going back to your view that "violence comes from believers", I very much agree that believers' choices are crucial. But I want to add a dimension of discussion: do you think the interpretation and practice of believers are completely independent of external social and historical factors? For example, in some regions that have experienced long-term colonial rule or geopolitical conflicts, religious conservatism tends to be more prominent. Is this a coincidence, or is it that the harsh living environment makes people more inclined to seek comfort in traditional religious interpretations? Let's take the Middle East as an example. Many Islamic countries have experienced the interference of external powers and the impact of wars. In such an environment, some conservative religious practices have emerged. At the same time, in some Western countries that have a stable social environment and a long history of modernization, Christian branches are more enlightened. When we compare these two phenomena, if we only focus on "the problem of believers" and ignore the differences in their living environments, will our evaluation be one-sided? Because this seems to ignore a fact: the initiative of believers' interpretation is also restricted by objective conditions. If we simply attribute the difference to "the quality or choice of believers", will we unconsciously overlook the impact of historical and political factors on religious practice? And this kind of one-sidedness, is it related to the fact that we are more familiar with the historical and social background of Western religions, but lack an in-depth understanding of non-Western religions?

Ladies and gentlemen, through the above discussion, we can find that the opposing debater's view that "religion itself is not violent, violence comes from believers" seems objective, but it ignores the hidden cognitive premise behind the evaluation of religious practice. First, when evaluating different religions, we may unconsciously be influenced by the dominant discourse environment, leading to inconsistent standards for judging progress and conservatism. Second, we may equate the Western understanding of gender equality with universal standards, ignoring the diversity of cultural expressions of equality. Third, we may overlook the impact of historical, political and social factors on believers' interpretation, and simply attribute the difference in religious practice to the choice of believers themselves.

These cognitive tendencies are not "prejudices" in the narrow sense, but unconscious cognitive biases formed by the limitations of our living environment and knowledge scope. However, it is precisely these biases that make us unable to view different religions and cultures from an objective and comprehensive perspective. The real significance of our discussion today is not to argue which religion is better, but to realize that when evaluating religious practice, we must first examine our own evaluation standards: whether we use consistent criteria, whether we respect cultural diversity, and whether we take into account the specific historical and social background.

The opposing debater's argument fails to recognize these hidden cognitive biases, so it cannot fully explain the complexity of religious practice. Therefore, his view is not comprehensive enough. Only by putting aside one-sided cognitive tendencies and respecting the diversity and complexity of different religions and cultures can we truly understand the essence of religious practice. Thank you!"""
            }
          ], # Replace with your prompt
    # thinking={"type": "disabled"}, #  Manually disable deep thinking
)
print(response.output[1].content[0].text)